### ISSUE TITLE
Button rendering problem

### ISSUE THREAD

**Issue by dbflakes** [Trendyol/react-carousel#12]
Thank you for this component. It's really helpful. I am facing one problem with rendering.
I followed the documentation at https://trendyol.github.io/react-carousel/docs/installation to install the library and use it in my project.

The carousel is being rendered as seen in the attached screenshot.
<img width="501" alt="Screen Shot 2021-02-20 at 00 01 18" src="https://user-images.githubusercontent.com/75661694/108588569-c3fff500-730e-11eb-879c-e58c628318e0.png">

My code:
```
import { ScrollingCarousel } from '@trendyol-js/react-carousel';

    const items = [];
    for (let i = 0; i < 20; i++) {
      items.push(
        <div style={{ width: '200px', height: '150px', backgroundColor: 'lightblue' }}>
          {i}
        </div>
      );
    }
    return (
      <ScrollingCarousel>
        {items}
      </ScrollingCarousel>
    );
```

I checked the installed package in node_modules and found the CSS files missing in the dist folder. So, I downloaded the source code and imported the CSS files directly in my code.
```
import '@trendyol-js/react-carousel/src/styles/styles.module.css';
import '@trendyol-js/react-carousel/src/styles/slider/styles.module.css';
```

The problem persists even after that.
Any help will be greatly appreciated.
Thanks.

**Comment by hasangenc0** [comment]
Hello @dbflakes, the package itself doesn't have any stylings for buttons. you should add custom CSS to align them properly.

Example snippet:
```css

button[data-direction] {
    top: calc(40% - 17px);
    width: 50px;
    height: 50px;
    display: block;
    cursor: pointer;
    border: none;
    position: absolute;
    background: url(<your-arrow.svg>) no-repeat center;
}
```

You can select buttons by `data-direction` attribute:

```css
button[data-direction='left'] { /* Left button */
    left: -55px;
    transform: rotateZ(180deg);
}
```

```css
button[data-direction='right'] { /* Right button */
    right: -55px;
}
```

Hope this is helpful for you, peace!
